# local_settings.py

# デバッグモードでの例外表示設定
DEBUG_PROPAGATE_EXCEPTIONS = True
